In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("c:\\Users\\shaba\\PycharmProjects\\Data-Analysis\\Data\\athlete_events.csv")
region_df = pd.read_csv("c:\\Users\\shaba\\PycharmProjects\\Data-Analysis\\Data\\noc_regions.csv")

In [3]:
df.sample(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
253965,127172,Sabine Vlker,F,32.0,162.0,58.0,Germany,GER,2006 Winter,2006,Winter,Torino,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
228856,114920,Valentina Sergeyevna Stenina (Miloslavova-),F,29.0,154.0,52.0,Soviet Union,URS,1964 Winter,1964,Winter,Innsbruck,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
7230,4047,Rafael Oliveira Andrade,M,30.0,168.0,58.0,Brazil,BRA,2016 Summer,2016,Summer,Rio de Janeiro,Trampolining,Trampolining Men's Individual,NaN
157698,79168,Darren Mew,M,20.0,194.0,83.0,Great Britain,GBR,2000 Summer,2000,Summer,Sydney,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN
192437,96623,Jeffrey Howard Campbell Powell,M,28.0,195.0,86.0,Canada,CAN,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Coxed Eights,NaN

In [4]:
region_df.sample(5)

     NOC              region notes
58   DOM  Dominican Republic   NaN
195  SYR               Syria   NaN
79   GER             Germany   NaN
38   CGO   Republic of Congo   NaN
194  SWZ           Swaziland   NaN

In [5]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [7]:
region_df.isnull().sum()

NOC         0
region      3
notes     209
dtype: int64

In [8]:
region_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     230 non-null    object
 1   region  227 non-null    object
 2   notes   21 non-null     object
dtypes: object(3)
memory usage: 5.5+ KB

In [9]:
df.duplicated().sum()

np.int64(1385)

In [10]:
df.shape

(271116, 15)

In [11]:
df.drop_duplicates(inplace =True)

In [12]:
df.shape

(269731, 15)

In [13]:
df = df[df.Season == 'Summer']

In [14]:
df.shape

(221167, 15)

In [15]:
df = pd.merge(df, region_df, on = "NOC", how="outer")

In [16]:
df['region'].unique()

array(['Afghanistan', 'Curacao', 'Albania', 'Algeria', 'Andorra',
       'Angola', 'Antigua', 'Australia', 'Argentina', 'Armenia', 'Aruba',
       'American Samoa', 'Austria', 'Azerbaijan', 'Bahamas', 'Bangladesh',
       'Barbados', 'Burundi', 'Belgium', 'Benin', 'Bermuda', 'Bhutan',
       'Bosnia and Herzegovina', 'Belize', 'Belarus', 'Czech Republic',
       'Boliva', 'Botswana', 'Brazil', 'Bahrain', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Central African Republic', 'Cambodia', 'Canada',
       'Cayman Islands', 'Republic of Congo', 'Chad', 'Chile', 'China',
       'Ivory Coast', 'Cameroon', 'Democratic Republic of the Congo',
       'Cook Islands', 'Colombia', 'Comoros', 'Cape Verde', 'Costa Rica',
       'Croatia', 'Greece', 'Cuba', 'Cyprus', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'Eritrea',
       'El Salvador', 'Spain', 'Estonia', 'Ethiopia', 'Russia', 'Fiji',
       'Finland', 'France', 'Germany', 'Micronesia', 'Gabon', 'Gambia',
       'UK', 'Guinea-Bissau', 'Georgia', 'Equatorial Guinea', 'Ghana',
       'Grenada', 'Guatemala', 'Guinea', 'Guam', 'Guyana', 'Haiti',
       'Honduras', 'Hungary', 'Indonesia', 'India',
       'Individual Olympic Athletes', 'Iran', 'Ireland', 'Iraq',
       'Iceland', 'Israel', 'Virgin Islands, US', 'Italy',
       'Virgin Islands, British', 'Jamaica', 'Jordan', 'Japan',
       'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Kiribati', 'South Korea',
       'Kosovo', 'Saudi Arabia', 'Kuwait', 'Laos', 'Latvia', 'Libya',
       'Liberia', 'Saint Lucia', 'Lesotho', 'Lebanon', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malaysia', 'Morocco',
       'Malawi', 'Moldova', 'Maldives', 'Mexico', 'Mongolia',
       'Marshall Islands', 'Macedonia', 'Mali', 'Malta', 'Montenegro',
       'Monaco', 'Mozambique', 'Mauritius', 'Mauritania', 'Myanmar',
       'Namibia', 'Nicaragua', 'Netherlands', 'Nepal', 'Nigeria', 'Niger',
       'Norway', 'Nauru', 'New Zealand', 'Oman', 'Pakistan', 'Panama',
       'Paraguay', 'Peru', 'Philippines', 'Palestine', 'Palau',
       'Papua New Guinea', 'Poland', 'Portugal', 'North Korea',
       'Puerto Rico', 'Qatar', 'Zimbabwe', nan, 'Romania', 'South Africa',
       'Rwanda', 'Samoa', 'Serbia', 'Senegal', 'Seychelles', 'Singapore',
       'Saint Kitts', 'Sierra Leone', 'Slovenia', 'San Marino',
       'Solomon Islands', 'Somalia', 'Sri Lanka', 'South Sudan',
       'Sao Tome and Principe', 'Sudan', 'Switzerland', 'Suriname',
       'Slovakia', 'Sweden', 'Swaziland', 'Syria', 'Tanzania', 'Tonga',
       'Thailand', 'Tajikistan', 'Turkmenistan', 'Timor-Leste', 'Togo',
       'Taiwan', 'Trinidad', 'Tunisia', 'Turkey', 'United Arab Emirates',
       'Uganda', 'Ukraine', 'Uruguay', 'USA', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Saint Vincent', 'Yemen', 'Zambia'],
      dtype=object)

In [17]:
df['Medal'].value_counts()

Medal
Gold      11456
Bronze    11409
Silver    11212
Name: count, dtype: int64

In [18]:
pd.get_dummies(df['Medal'], dtype = int)

        Bronze  Gold  Silver
0            0     0       0
1            0     0       0
2            0     0       0
3            0     0       0
4            0     0       0
...        ...   ...     ...
221163       0     0       0
221164       0     0       0
221165       0     0       0
221166       0     0       0
221167       0     0       0

[221168 rows x 3 columns]

In [19]:
df =pd.concat([df, pd.get_dummies(df['Medal'], dtype = int)], axis = 1)

In [28]:
medal_tally = df.drop_duplicates(subset = ['Team','NOC', 'Games', 'Year', 'City', 'Sport', 'Event' ,'Medal'])

In [21]:
medal_tally = medal_tally.groupby('NOC').sum()[['Gold','Silver','Bronze']].sort_values('Gold', ascending = False).reset_index()

In [22]:
medal_tally['Total'] = medal_tally['Gold'] + medal_tally['Silver'] + medal_tally['Bronze']

In [23]:
medal_tally

     NOC  Gold  Silver  Bronze  Total
0    USA  1035     802     708   2545
1    URS   394     317     294   1005
2    GBR   278     317     300    895
3    GER   235     261     283    779
4    FRA   234     256     287    777
..   ...   ...     ...     ...    ...
226  WIF     0       0       2      2
227  YEM     0       0       0      0
228  YAR     0       0       0      0
229  YMD     0       0       0      0
230  ZAM     0       1       1      2

[231 rows x 5 columns]

In [24]:
df.dropna(subset=['Year'], inplace=True)
years = df['Year'].astype('int').unique().tolist()
years.sort()
years.insert(0, 'Overall')

In [25]:
country = np.unique(df['region'].dropna().values).tolist()
country.sort()
country.insert(0, 'Overall')

In [31]:
medal_df = df.drop_duplicates(subset = ['Team','NOC', 'Games', 'Year', 'City', 'Sport', 'Event' ,'Medal'])

In [65]:
medal_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,502.0,Ahmad Shah Abouwi,M,NaN,NaN,NaN,Afghanistan,AFG,1956 Summer,1956.0,Summer,Melbourne,Hockey,Hockey Men's Hockey,NaN,Afghanistan,NaN,0,0,0
1,1076.0,Jammal-ud-Din Affendi,M,28.0,NaN,NaN,Afghanistan,AFG,1936 Summer,1936.0,Summer,Berlin,Hockey,Hockey Men's Hockey,NaN,Afghanistan,NaN,0,0,0
2,1101.0,Mohammad Anwar Afzal,M,NaN,NaN,NaN,Afghanistan,AFG,1948 Summer,1948.0,Summer,London,Football,Football Men's Football,NaN,Afghanistan,NaN,0,0,0
3,1745.0,Mohammad Aktar,M,17.0,156.0,48.0,Afghanistan,AFG,1980 Summer,1980.0,Summer,Moskva,Wrestling,"Wrestling Men's Light-Flyweight, Freestyle",NaN,Afghanistan,NaN,0,0,0
4,4628.0,Mohammad Daoud Anwary,M,22.0,NaN,NaN,Afghanistan,AFG,1964 Summer,1964.0,Summer,Tokyo,Wrestling,"Wrestling Men's Bantamweight, Freestyle",NaN,Afghanistan,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221160,130453.0,Antonette Wilken (-Batchelor),F,19.0,162.0,49.0,Zimbabwe,ZIM,1980 Summer,1980.0,Summer,Moskva,Diving,Diving Women's Platform,NaN,Zimbabwe,NaN,0,0,0
221162,130832.0,Hillary Wilson,F,15.0,157.0,65.0,Zimbabwe,ZIM,1960 Summer,1960.0,Summer,Roma,Swimming,Swimming Women's 400 metres Freestyle,NaN,Zimbabwe,NaN,0,0,0
221163,130832.0,Hillary Wilson,F,15.0,157.0,65.0,Zimbabwe,ZIM,1960 Summer,1960.0,Summer,Roma,Swimming,Swimming Women's 100 metres Butterfly,NaN,Zimbabwe,NaN,0,0,0
221165,130880.0,Peter Arthur Wilson,M,20.0,185.0,80.0,Zimbabwe,ZIM,1980 Summer,1980.0,Summer,Moskva,Sailing,Sailing Mixed One Person Dinghy,NaN,Zimbabwe,NaN,0,0,0
221166,131478.0,"Jennifer ""Jenny"" Wood",F,16.0,172.0,64.0,Zimbabwe,ZIM,1964 Summer,1964.0,Summer,Tokyo,Swimming,Swimming Women's 100 metres Butterfly,NaN,Zimbabwe,NaN,0,0,0

In [110]:
def fetch_medal_tally(year, country):
    flag = 0
    medal_df['Year']=medal_df['Year'].astype('int')
    if year == 'Overall' and country == 'Overall':
        temp_df = medal_df
    if year != 'Overall' and country == 'Overall':
        temp_df = medal_df[medal_df['Year']== year]
    if year == 'Overall' and country != 'Overall':
        flag = 1
        temp_df = medal_df[medal_df['region']== country]
    if year != 'Overall' and country != 'Overall':
        temp_df = medal_df[(medal_df['Year']== year) & (medal_df['region'] == country)]

    if flag == 1:
        x = temp_df.groupby('Year').sum()[['Gold','Silver','Bronze']].sort_values('Year').reset_index()
    else:
        x = temp_df.groupby('region').sum()[['Gold','Silver','Bronze']].sort_values('Gold', ascending=False).reset_index()
    
    x['Total'] = x['Gold'] + x['Silver'] + x['Bronze']
    print(x)

In [111]:
fetch_medal_tally('Overall', 'India')

    Year  Gold  Silver  Bronze  Total
0   1900     0       2       0      2
1   1920     0       0       0      0
2   1924     0       0       0      0
3   1928     1       0       0      1
4   1932     1       0       0      1
5   1936     1       0       0      1
6   1948     1       0       0      1
7   1952     1       0       1      2
8   1956     1       0       0      1
9   1960     0       1       0      1
10  1964     1       0       0      1
11  1968     0       0       1      1
12  1972     0       0       1      1
13  1976     0       0       0      0
14  1980     1       0       0      1
15  1984     0       0       0      0
16  1988     0       0       0      0
17  1992     0       0       0      0
18  1996     0       0       1      1
19  2000     0       0       1      1
20  2004     0       1       0      1
21  2008     1       0       2      3
22  2012     0       2       4      6
23  2016     0       1       1      2

C:\Users\shaba\AppData\Local\Temp\ipykernel_4148\488241192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medal_df['Year']=medal_df['Year'].astype('int')

In [18]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,502.0,Ahmad Shah Abouwi,M,NaN,NaN,NaN,Afghanistan,AFG,1956 Summer,1956.0,Summer,Melbourne,Hockey,Hockey Men's Hockey,NaN,Afghanistan,NaN
1,1076.0,Jammal-ud-Din Affendi,M,28.0,NaN,NaN,Afghanistan,AFG,1936 Summer,1936.0,Summer,Berlin,Hockey,Hockey Men's Hockey,NaN,Afghanistan,NaN
2,1101.0,Mohammad Anwar Afzal,M,NaN,NaN,NaN,Afghanistan,AFG,1948 Summer,1948.0,Summer,London,Football,Football Men's Football,NaN,Afghanistan,NaN
3,1745.0,Mohammad Aktar,M,17.0,156.0,48.0,Afghanistan,AFG,1980 Summer,1980.0,Summer,Moskva,Wrestling,"Wrestling Men's Light-Flyweight, Freestyle",NaN,Afghanistan,NaN
4,4628.0,Mohammad Daoud Anwary,M,22.0,NaN,NaN,Afghanistan,AFG,1964 Summer,1964.0,Summer,Tokyo,Wrestling,"Wrestling Men's Bantamweight, Freestyle",NaN,Afghanistan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221163,130832.0,Hillary Wilson,F,15.0,157.0,65.0,Zimbabwe,ZIM,1960 Summer,1960.0,Summer,Roma,Swimming,Swimming Women's 100 metres Butterfly,NaN,Zimbabwe,NaN
221164,130832.0,Hillary Wilson,F,15.0,157.0,65.0,Zimbabwe,ZIM,1960 Summer,1960.0,Summer,Roma,Swimming,Swimming Women's 4 x 100 metres Medley Relay,NaN,Zimbabwe,NaN
221165,130880.0,Peter Arthur Wilson,M,20.0,185.0,80.0,Zimbabwe,ZIM,1980 Summer,1980.0,Summer,Moskva,Sailing,Sailing Mixed One Person Dinghy,NaN,Zimbabwe,NaN
221166,131478.0,"Jennifer ""Jenny"" Wood",F,16.0,172.0,64.0,Zimbabwe,ZIM,1964 Summer,1964.0,Summer,Tokyo,Swimming,Swimming Women's 100 metres Butterfly,NaN,Zimbabwe,NaN
221167,135497.0,Lloyd Zvasiya,M,23.0,190.0,80.0,Zimbabwe,ZIM,2004 Summer,2004.0,Summer,Athina,Athletics,Athletics Men's 400 metres,NaN,Zimbabwe,NaN

In [19]:
countries = df['region'].unique().shape

In [23]:
editions = df['Year'].unique().shape[0] - 1

In [22]:
cities = df['City'].unique().shape

In [24]:
import plotly.express as px

In [31]:
countries_over_years =df.drop_duplicates(['Year', 'region'])['Year'].value_counts().reset_index().sort_values('Year')

In [32]:
px.line(countries_over_years,x= 'Year', y = 'count')